export enum AddressName {
  ICHI_BNT = 'ICHI_BNT',
  ICHI_BNT_V3 = 'ICHI_BNT_V3',
  ICHIBPT = 'ICHIBPT',
  ETH = 'ETH',
  ALLY = 'ALLY',
  FARMING_V1 = 'FARMING_V1',
  FARMING_V2 = 'FARMING_V2',
  FARMING_V3 = 'FARMING_V3',
  ICHI_COMMUNITY_GNOSIS = 'ICHI_COMMUNITY_GNOSIS',
  ICHI_V2_GNOSIS = 'ICHI_V2_GNOSIS',
  UNISWAP_V3_POSITIONS = 'UNISWAP_V3_POSITIONS',
  _1INCH_ICHI_LP = '_1INCH_ICHI_LP',
  _1INCH_STAKING = '_1INCH_STAKING',
  ST1INCH = 'ST1INCH',
  BMI_STAKING = 'BMI_STAKING',
  // RISK_HARBOR= // RISK_HARBOR,
  RARI_POOL_LENS = 'RARI_POOL_LENS',
  RARI_POOL_LENS_SECONDARY = 'RARI_POOL_LENS_SECONDARY',
  RARI_ONEUNI_TOKEN = 'RARI_ONEUNI_TOKEN',
  RARI_ICHI_VAULT_LP_TOKEN = 'RARI_ICHI_VAULT_LP_TOKEN',
  RARI_ONEBTC_VAULT_LP_TOKEN = 'RARI_ONEBTC_VAULT_LP_TOKEN',
  RARI_COMPTROLLER = 'RARI_COMPTROLLER',
  RARI_ONEUNI = 'RARI_ONEUNI',
  RARI_ONEBTC = 'RARI_ONEBTC',
  RARI_USDC = 'RARI_USDC',
  RARI_WBTC = 'RARI_WBTC',
  GSR = 'GSR',

  // BSC
  GNOSIS = 'GNOSIS',
  USDC = 'USDC',
  ONE_DODO = 'ONE_DODO',
  DLP = 'DLP'
}
export type AddressNames = keyof typeof AddressName;
export type AddressValues = typeof AddressName[keyof typeof AddressName];
