export enum PoolGroupName {
  ACTIVE_POOLS = 'ACTIVE_POOLS',
  DEPOSIT_POOLS = 'DEPOSIT_POOLS',
  ACTIVE_VAULTS = 'ACTIVE_VAULTS',
  UPCOMING_POOLS = 'UPCOMING_POOLS',
  MIGRATING_POOLS = 'MIGRATING_POOLS',
  RETIRED_POOLS = 'RETIRED_POOLS',
  UNRETIRED_POOLS = 'UNRETIRED_POOLS',
  ACTIVE_APR = 'ACTIVE_APR',
  UNDERLYING_VAULTS = 'UNDERLYING_VAULTS',
  ONE_INCH_POOLS = 'ONE_INCH_POOLS',
  BALANCER_POOLS = 'BALANCER_POOLS',
  BALANCER_SMART_POOLS = 'BALANCER_SMART_POOLS',
  BANCOR_POOLS_V2 = 'BANCOR_POOLS_V2',
  BANCOR_POOLS_V3 = 'BANCOR_POOLS_V3',
  UNI_POOLS = 'UNI_POOLS',
  LOOPRING_POOLS = 'LOOPRING_POOLS',
  DODO_POOLS = 'DODO_POOLS',
  RARI_ASSETS = 'RARI_ASSETS',
  SPECIAL_PRICING = 'SPECIAL_PRICING',
  LEGACY_POOLS = 'LEGACY_POOLS',
  HIDDEN_VAULTS = 'HIDDEN_VAULTS'
}

export type PoolGroupNames = keyof typeof PoolGroupName;
