import { TokenName } from '../enums/tokenName';
import { PoolName } from '../enums/poolName';
import { ChainId } from '../crypto/networks';
import { Pool } from '../models/pool';
import { PartialRecord } from '../types/common';
import { PoolGroupName } from '../enums/poolManagementName';
import { 
  ArbitrumPoolNumbers,
  ArbitrumPoolNumberValues,
  AvalanchePoolNumberValues,
  BscPoolNumbers,
  BscPoolNumberValues,
  EonPoolNumbers,
  EonPoolNumberValues,
  FantomPoolNumbers,
  FantomPoolNumberValues,
  LineaPoolNumbers,
  LineaPoolNumberValues,
  MainnetPoolNumbers, 
  MainnetPoolNumberValues, 
  MantlePoolNumbers, 
  MantlePoolNumberValues, 
  MumbaiPoolNumbers, 
  MumbaiPoolNumberValues, 
  OpBnbPoolNumbers, 
  OpBnbPoolNumberValues, 
  PolygonPoolNumbers, 
  PolygonPoolNumberValues,
  ZkEvmPoolNumbers,
  ZkEvmPoolNumberValues,
  ZkSyncPoolNumbers,
  ZkSyncPoolNumberValues, 
} from '../enums/poolNumber';

type TPoolMapping = { [vaultName in PoolName]: PartialRecord<ChainId, Pool> };
// NOTE: To some degree it's more logical to namespace with Network then PoolName, but actually
// it get's annoying to scroll to the Network you want while coding, and better dev exp
// to find the Pool in question then you can see all info right there.  Either way would work, but this
// is the way we've chosen.
export const PoolMapping: TPoolMapping = {
  [PoolName.ONEFUSE_USDC]: {
    [ChainId.Mainnet]: {
      poolName: PoolName.ONEFUSE_USDC,
      tableName: PoolName.ONEFUSE_USDC,
      displayName: 'oneFUSE-USDC',
      address: '0x61f2ea3ddabcb9f0b7bd73adba4ec24479247a86',
      oneTokenName: TokenName.ONE_FUSE,
      oneToken: 'token1',
      enableNotifications: false,
    },
  },
  // [PoolName.ONEUNI_USDC]: {
  //   [ChainId.Mainnet]: {
  //     poolName: PoolName.ONEUNI_USDC,
  //     tableName: PoolName.ONEUNI_USDC,
  //     displayName: 'oneUNI-USDC',
  //     address: '0x613944734e29e73d084673d1532bff8683ed9a5b',
  //     oneTokenName: TokenName.ONE_UNI,
  //     oneToken: 'token0',
  //     enableNotifications: false
  //   }
  // },
  // [PoolName.ONEWING_USDC]: {
  //   [ChainId.Mainnet]: {
  //     poolName: PoolName.ONEWING_USDC,
  //     tableName: PoolName.ONEWING_USDC,
  //     displayName: 'oneWING-USDC',
  //     address: '0xD63005e1d0bD8029B656dd43AD8eB66f27B15E07',
  //     oneTokenName: TokenName.ONE_WING,
  //     oneToken: 'token0',
  //     enableNotifications: false
  //   }
  // },
  // [PoolName.ONEFOX_USDC]: {
  //   [ChainId.Mainnet]: {
  //     poolName: PoolName.ONEFOX_USDC,
  //     tableName: PoolName.ONEFOX_USDC,
  //     displayName: 'oneFOX-USDC',
  //     address: '0x4c008261215087bd22d6a983399ae659d816bb50',
  //     : TokenName.ONE_FOX,
  //     oneToken: 'token0',
  //     enableNotifications: false
  //   }
  // },
  [PoolName.ONEPERL_USDC]: {
    [ChainId.Mainnet]: {
      poolName: PoolName.ONEPERL_USDC,
      tableName: PoolName.ONEPERL_USDC,
      displayName: 'onePERL-USDC',
      address: '0x1F52846051b4dB60ba70bA76C188e6a67699fdB0',
      oneTokenName: TokenName.ONE_PERL,
      oneToken: 'token1',
      enableNotifications: false,
    },
  },
  // [PoolName.ONEMPH_USDC]: {
  //   [ChainId.Mainnet]: {
  //     poolName: PoolName.ONEMPH_USDC,
  //     tableName: PoolName.ONEMPH_USDC,
  //     displayName: 'oneMPH-USDC',
  //     address: '0x42F1B1a352B4e700172F316eC5f721765a71EfF4',
  //     oneTokenName: TokenName.ONE_MPH,
  //     oneToken: 'token1',
  //     enableNotifications: false
  //   }
  // },
  [PoolName.ONE1INCH_USDC]: {
    [ChainId.Mainnet]: {
      poolName: PoolName.ONE1INCH_USDC,
      tableName: PoolName.ONE1INCH_USDC,
      displayName: 'one1INCH-USDC',
      address: '0x7233A14685201F548d8a7AC5f5Ca3DEdb7bb6d42',
      oneTokenName: TokenName.ONE_1INCH,
      oneToken: 'token0',
      enableNotifications: false,
    },
  },
  [PoolName.ONEGIV_DAI]: {
    [ChainId.Mainnet]: {
      poolName: PoolName.ONEGIV_DAI,
      tableName: PoolName.ONEGIV_DAI,
      displayName: 'oneGIV-DAI',
      address: '0xC506ca6089648D3Fc22dEb5CFAbb8F01f39D4eaF',
      oneTokenName: TokenName.ONE_GIV,
      oneToken: 'token0',
      enableNotifications: false,
      otherToken: TokenName.DAI,
    },
  },
  [PoolName.ONEICHI_USDC]: {
    [ChainId.Mainnet]: {
      poolName: PoolName.ONEICHI_USDC,
      tableName: PoolName.ONEICHI_USDC,
      displayName: 'oneICHI-USDC',
      address: '0xF836a9268d39C89c9C8533BF97e93C00E25dC13e',
      oneTokenName: TokenName.ONE_ICHI,
      oneToken: 'token0',
      enableNotifications: false,
    },
  },
  // [PoolName.ONEOJA_USDC]: {
  //   [ChainId.Mainnet]: {
  //     poolName: PoolName.ONEOJA_USDC,
  //     tableName: PoolName.ONEOJA_USDC,
  //     displayName: 'oneOJA-USDC',
  //     address: '0x6195fe3c13746862deac6139c4e8be5e80b96c6c',
  //     oneTokenName: TokenName.ONE_OJA,
  //     oneToken: 'token1',
  //     enableNotifications: false
  //   }
  // }

  // Polygon
  // onebtc_ichi: {
  //   displayName: 'oneBTC-USDC',
  //   address: '0x8324be628543be4a8ee4448c1a269cad3da487f6',
  //   oneTokenName: 'onebtc',
  //   oneToken: 'token1',
  //   enableNotifications: false,
  // },
};

type TPools = {
  // [poolGroupName in PoolGroupName]: Record<ChainId, PoolNumberValues[]>
  [poolGroupName in PoolGroupName]: {
    [ChainId.Mainnet]: MainnetPoolNumberValues[];
    [ChainId.Arbitrum]: ArbitrumPoolNumberValues[];
    [ChainId.Avalanche]: AvalanchePoolNumberValues[];
    [ChainId.Bsc]: BscPoolNumberValues[];
    [ChainId.Eon]: EonPoolNumberValues[];
    [ChainId.Fantom]: FantomPoolNumberValues[];
    [ChainId.Linea]: LineaPoolNumberValues[];
    [ChainId.Mantle]: MantlePoolNumberValues[];
    [ChainId.opBNB]: OpBnbPoolNumberValues[];
    [ChainId.Polygon]: PolygonPoolNumberValues[];
    [ChainId.zkEVM]: ZkEvmPoolNumberValues[];
    [ChainId.zkSync]: ZkSyncPoolNumberValues[];
    [ChainId.Mumbai]: MumbaiPoolNumberValues[];
  };
};

export const Pools: TPools = {
  [PoolGroupName.ACTIVE_POOLS]: {
    [ChainId.Mainnet]: [
      MainnetPoolNumbers._80_20_ICHI_ETH,
      MainnetPoolNumbers.ICHI_1INCH,
      MainnetPoolNumbers.ICHI_BNT,
      MainnetPoolNumbers.ICHI_BNT_V3,
      MainnetPoolNumbers.ICHI_ETH_SUSHI,
      MainnetPoolNumbers.ICHI_ETH_UNI_V2,
      MainnetPoolNumbers.ONE_1INCH,
      MainnetPoolNumbers.ONE_BTC_DEPOSIT,
      MainnetPoolNumbers.ONE_DODO,
      MainnetPoolNumbers.ONE_FIL,
      MainnetPoolNumbers.ONE_FOX,
      MainnetPoolNumbers.ONE_MPH,
      MainnetPoolNumbers.ONE_PERL,
      MainnetPoolNumbers.ONE_UNI,
      MainnetPoolNumbers.ONE_WING,
    ],
    [ChainId.Polygon]: [],
    [ChainId.Arbitrum]: [],
    [ChainId.Avalanche]: [],
    [ChainId.Bsc]: [],
    [ChainId.Eon]: [],
    [ChainId.Fantom]: [],
    [ChainId.Linea]: [],
    [ChainId.Mantle]: [],
    [ChainId.opBNB]: [],
    [ChainId.zkEVM]: [],
    [ChainId.zkSync]: [],
    [ChainId.Mumbai]: [],
  },
  [PoolGroupName.DEPOSIT_POOLS]: {
    [ChainId.Mainnet]: [
      MainnetPoolNumbers.ONE_1INCH, 
      MainnetPoolNumbers.ONE_BTC_DEPOSIT,
      MainnetPoolNumbers.ONE_DODO, 
      MainnetPoolNumbers.ONE_FIL, 
      MainnetPoolNumbers.ONE_FOX, 
      MainnetPoolNumbers.ONE_MPH, 
      MainnetPoolNumbers.ONE_PERL, 
      MainnetPoolNumbers.ONE_UNI, 
      MainnetPoolNumbers.ONE_WING, 
    ],
    [ChainId.Polygon]: [],
    [ChainId.Arbitrum]: [],
    [ChainId.Avalanche]: [],
    [ChainId.Bsc]: [],
    [ChainId.Eon]: [],
    [ChainId.Fantom]: [],
    [ChainId.Linea]: [],
    [ChainId.Mantle]: [],
    [ChainId.opBNB]: [],
    [ChainId.zkEVM]: [],
    [ChainId.zkSync]: [],
    [ChainId.Mumbai]: [],
  },
  // these vaults are processed by api-updater. 
  // All vaults for new and legacy apps are added here.
  [PoolGroupName.ACTIVE_VAULTS]: {
    [ChainId.Mainnet]: [
      MainnetPoolNumbers['1INCH_VAULT'],
      MainnetPoolNumbers.AAVE_VAULT,
      MainnetPoolNumbers.ALLY_VAULT,
      MainnetPoolNumbers.ASTO_VAULT,
      MainnetPoolNumbers.BANK_VAULT,
      MainnetPoolNumbers.BAT_VAULT,
      MainnetPoolNumbers.BIT_VAULT,
      MainnetPoolNumbers.BNT_VAULT,
      MainnetPoolNumbers.BOBA_VAULT,
      MainnetPoolNumbers.BOBA_ETH_VAULT,
      MainnetPoolNumbers.CEL_VAULT,
      MainnetPoolNumbers.CEL_VAULT_LEGACY,
      MainnetPoolNumbers.CHO_VAULT,
      MainnetPoolNumbers.COC_VAULT,
      MainnetPoolNumbers.COC_USDC_VAULT,
      MainnetPoolNumbers.COC_ETH_VAULT,
      MainnetPoolNumbers.COMP_VAULT,
      MainnetPoolNumbers.COW_VAULT,
      MainnetPoolNumbers.GNO_VAULT,
      MainnetPoolNumbers.GNO_VAULT_LEGACY,
      MainnetPoolNumbers.FIDU_VAULT,
      MainnetPoolNumbers.FRAX_VAULT,
      MainnetPoolNumbers.FUSE_ICHI_VAULT,
      MainnetPoolNumbers.FXS_VAULT,
      MainnetPoolNumbers.GIV_VAULT,
      MainnetPoolNumbers.GIV_ETH_VAULT,
      MainnetPoolNumbers.HOME_VAULT,
      MainnetPoolNumbers.ICHI_ETH_VAULT,
      MainnetPoolNumbers.ICHI_USDC_VAULT,
      MainnetPoolNumbers.ICHI_WBTC_VAULT,
      MainnetPoolNumbers.IMX_VAULT,
      MainnetPoolNumbers.IMX_ETH_VAULT,
      MainnetPoolNumbers.IMX_ICHI_1_VAULT,
      MainnetPoolNumbers.LDO_VAULT,
      MainnetPoolNumbers.LINK_VAULT,
      MainnetPoolNumbers.LMR_WETH_VAULT,
      MainnetPoolNumbers.MET_WETH_VAULT,
      MainnetPoolNumbers.METIS_VAULT,
      MainnetPoolNumbers.MIDAS_VAULT,
      MainnetPoolNumbers.MKR_VAULT,
      MainnetPoolNumbers.OGN_VAULT,
      MainnetPoolNumbers.ONE_BTC_VAULT_RARI,
      MainnetPoolNumbers.ONE_FUSE_VAULT,
      MainnetPoolNumbers.ONE_FOX_VAULT,
      MainnetPoolNumbers.ONE_GIV,
      MainnetPoolNumbers.ONE_ICHI_VAULT,
      MainnetPoolNumbers.ONE_OJA_VAULT,
      MainnetPoolNumbers.ONE_UNI_VAULT,
      MainnetPoolNumbers.ONE_UNI_VAULT_LP,
      MainnetPoolNumbers.ONE_WING_VAULT,
      MainnetPoolNumbers.OUSD_VAULT,
      MainnetPoolNumbers.QRDO_VAULT,
      MainnetPoolNumbers.QRDO_ICHI_VAULT,
      MainnetPoolNumbers.SFRXETH_VAULT,
      MainnetPoolNumbers.SHIB_VAULT,
      MainnetPoolNumbers.SUSHI_VAULT,
      MainnetPoolNumbers.SWISE_VAULT,
      MainnetPoolNumbers.TBTC_WETH_VAULT,
      MainnetPoolNumbers.UMA_VAULT,
      MainnetPoolNumbers.UNI_VAULT, 
      MainnetPoolNumbers.USDC_VAULT,
      MainnetPoolNumbers.WBTC_VAULT,
      MainnetPoolNumbers.WBTC_VAULT_LEGACY,
      MainnetPoolNumbers.WETH_ABOND_VAULT,
      MainnetPoolNumbers.WETH_VAULT,
      MainnetPoolNumbers.WETH_GARBAGE_VAULT,
      MainnetPoolNumbers.WNXM_VAULT,
      MainnetPoolNumbers.WNXM_VAULT_LEGACY,
      MainnetPoolNumbers.YFI_VAULT,
      MainnetPoolNumbers.ZRX_VAULT,
      // PancakeSwap
      MainnetPoolNumbers.PANCAKESWAP_SWETH_WETH_VAULT,
      MainnetPoolNumbers.PANCAKESWAP_WETH_SWETH_VAULT,
      MainnetPoolNumbers.PANCAKESWAP_WETH_USDT_VAULT,
    ],
    [ChainId.Polygon]: [
      PolygonPoolNumbers.A3A_EURO3_VAULT, 
      PolygonPoolNumbers.BAL_WETH_VAULT, 
      PolygonPoolNumbers.CRV_WETH_VAULT, 
      PolygonPoolNumbers.DPI_WETH_VAULT, 
      PolygonPoolNumbers.EURO3_A3A_VAULT, 
      PolygonPoolNumbers.FBX_WSTETH_VAULT, 
      PolygonPoolNumbers.GHST_WETH_VAULT, 
      PolygonPoolNumbers.GOVI_VAULT, 
      PolygonPoolNumbers.ICHI_USDC_VAULT, 
      PolygonPoolNumbers.ICHI_WBTC_VAULT, 
      PolygonPoolNumbers.ICHI_WETH_VAULT, 
      PolygonPoolNumbers.ICHI_WMATIC_VAULT, 
      PolygonPoolNumbers.LINK_WETH_VAULT, 
      PolygonPoolNumbers.ONE_BTC_VAULT, 
      PolygonPoolNumbers.OXT_WETH_VAULT, 
      PolygonPoolNumbers.POP_WETH_VAULT, 
      PolygonPoolNumbers.SUSHI_WETH_VAULT, 
      PolygonPoolNumbers.TRADE_USDT_VAULT, 
      PolygonPoolNumbers.USDC_EURO3_VAULT, 
      PolygonPoolNumbers.USDC_VAULT, 
      PolygonPoolNumbers.USDC_WETH_VAULT,
      PolygonPoolNumbers.WBTC_VAULT, 
      PolygonPoolNumbers.WBTC_WETH_VAULT, 
      PolygonPoolNumbers.WEN_WETH_VAULT, 
      PolygonPoolNumbers.WETH_FBX_VAULT, 
      PolygonPoolNumbers.WETH_USDC_VAULT, 
      PolygonPoolNumbers.WMATIC_WETH_VAULT, 
      PolygonPoolNumbers.WSTETH_FBX_VAULT, 
      PolygonPoolNumbers.WSTETH_WETH_VAULT,
      // QuickSwap
      PolygonPoolNumbers.QUICKSWAP_A3A_USDC_VAULT,
      PolygonPoolNumbers.QUICKSWAP_AAVE_WETH_VAULT,
      PolygonPoolNumbers.QUICKSWAP_LINK_WETH_VAULT,
      PolygonPoolNumbers.QUICKSWAP_MATICX_WMATIC_VAULT,
      PolygonPoolNumbers.QUICKSWAP_USDC_A3A_VAULT,
      PolygonPoolNumbers.QUICKSWAP_USDC_ABOND_VAULT,
      PolygonPoolNumbers.QUICKSWAP_USDC_QUICK_VAULT,
      PolygonPoolNumbers.QUICKSWAP_USDC_WEFI_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WBTC_USDC_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WBTC_WETH_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WEFI_USDC_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WEFI_WETH_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WETH_FUSE_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WETH_ICHI_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WETH_QUICK_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WETH_USDT_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WETH_WEFI_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WMATIC_ABOND_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WMATIC_ICHI_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WMATIC_QUICK_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WMATIC_USDT_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WMATIC_WETH_VAULT,
      // Retro 
      PolygonPoolNumbers.RETRO_AGEUR_RETRO_VAULT,
      PolygonPoolNumbers.RETRO_AGEUR_USDC_VAULT,
      PolygonPoolNumbers.RETRO_CASH_AXLLQDR_VAULT, 
      PolygonPoolNumbers.RETRO_CASH_ICHI_VAULT,
      PolygonPoolNumbers.RETRO_CASH_RETRO_VAULT,
      PolygonPoolNumbers.RETRO_CASH_WETH_VAULT, 
      PolygonPoolNumbers.RETRO_CASH_WMATIC_VAULT, 
      PolygonPoolNumbers.RETRO_FRXETH_FRAX_VAULT,
      PolygonPoolNumbers.RETRO_FRXETH_WMATIC_VAULT,
      PolygonPoolNumbers.RETRO_ICHI_CASH_VAULT,
      PolygonPoolNumbers.RETRO_ICHI_RETRO_VAULT,
      PolygonPoolNumbers.RETRO_JRT_WETH_VAULT,
      PolygonPoolNumbers.RETRO_LINK_RETRO_VAULT,
      PolygonPoolNumbers.RETRO_MATICX_CASH_VAULT, 
      PolygonPoolNumbers.RETRO_MATICX_WMATIC_01_VAULT,
      PolygonPoolNumbers.RETRO_MATICX_WMATIC_05_VAULT,
      PolygonPoolNumbers.RETRO_MIMATIC_RETRO_VAULT,
      PolygonPoolNumbers.RETRO_OATH_WETH_VAULT,
      PolygonPoolNumbers.RETRO_ORETRO_RETRO_VAULT,
      PolygonPoolNumbers.RETRO_RETRO_LIVERETRO_VAULT,
      PolygonPoolNumbers.RETRO_STMATIC_RETRO_VAULT,
      PolygonPoolNumbers.RETRO_STMATIC_WMATIC_VAULT,
      PolygonPoolNumbers.RETRO_USDC_AGEUR_VAULT,
      PolygonPoolNumbers.RETRO_USDC_MIMATIC_VAULT,
      PolygonPoolNumbers.RETRO_USDC_RETRO_VAULT,
      PolygonPoolNumbers.RETRO_USDC_WETH_VAULT, 
      PolygonPoolNumbers.RETRO_USDC_WMATIC_VAULT, 
      PolygonPoolNumbers.RETRO_USDT_RETRO_VAULT,
      PolygonPoolNumbers.RETRO_USDT_WMATIC_VAULT, 
      PolygonPoolNumbers.RETRO_WBTC_RETRO_VAULT,
      PolygonPoolNumbers.RETRO_WBTC_USDC_VAULT,
      PolygonPoolNumbers.RETRO_WBTC_WETH_VAULT, 
      PolygonPoolNumbers.RETRO_WETH_ERN_VAULT,
      PolygonPoolNumbers.RETRO_WETH_OATH_VAULT,
      PolygonPoolNumbers.RETRO_WETH_RETRO_VAULT,
      PolygonPoolNumbers.RETRO_WETH_USDC_VAULT,
      PolygonPoolNumbers.RETRO_WETH_WBTC_VAULT, 
      PolygonPoolNumbers.RETRO_WETH_WMATIC_VAULT, 
      PolygonPoolNumbers.RETRO_WMATIC_ICHI_VAULT,
      PolygonPoolNumbers.RETRO_WMATIC_MATICX_01_VAULT,
      PolygonPoolNumbers.RETRO_WMATIC_MATICX_05_VAULT,
      PolygonPoolNumbers.RETRO_WMATIC_RETRO_VAULT,
      PolygonPoolNumbers.RETRO_WMATIC_STMATIC_VAULT,
      PolygonPoolNumbers.RETRO_WMATIC_USDC_VAULT, 
      PolygonPoolNumbers.RETRO_WMATIC_USDC_05_VAULT,
      PolygonPoolNumbers.RETRO_WMATIC_WETH_VAULT, 
    ],
    [ChainId.Arbitrum]: [
      ArbitrumPoolNumbers.ARB_ICHI_VAULT,
      ArbitrumPoolNumbers.ARB_WBTC_VAULT,
      ArbitrumPoolNumbers.ARB_WETH_VAULT,
      ArbitrumPoolNumbers.L2DAO_WETH_VAULT,
      ArbitrumPoolNumbers.LMR_WBTC_VAULT,
      ArbitrumPoolNumbers.LMR_WETH_VAULT,
      ArbitrumPoolNumbers.USDC_ICHI_VAULT,
      ArbitrumPoolNumbers.WBTC_ICHI_VAULT,
      ArbitrumPoolNumbers.WETH_ICHI_VAULT,
      ArbitrumPoolNumbers.WETH_LMR_VAULT,
      // Horiza
      ArbitrumPoolNumbers.HORIZA_USDC_ICHI_VAULT,
      ArbitrumPoolNumbers.HORIZA_WETH_ICHI_VAULT,
      // Ramses
      ArbitrumPoolNumbers.RAMSES_ARB_RAM_VAULT,
      ArbitrumPoolNumbers.RAMSES_ARB_USDC_VAULT,
      ArbitrumPoolNumbers.RAMSES_ARB_WETH_VAULT,
      ArbitrumPoolNumbers.RAMSES_FRAX_USDC_VAULT,
      ArbitrumPoolNumbers.RAMSES_FRXETH_WETH_VAULT,
      ArbitrumPoolNumbers.RAMSES_GRAI_RAM_VAULT,
      ArbitrumPoolNumbers.RAMSES_GRAI_WETH_VAULT,
      ArbitrumPoolNumbers.RAMSES_ICHI_RAM_VAULT,
      ArbitrumPoolNumbers.RAMSES_OATH_WETH_VAULT,
      ArbitrumPoolNumbers.RAMSES_SFRAX_FRAX_VAULT,
      ArbitrumPoolNumbers.RAMSES_USDC_ARB_VAULT,
      ArbitrumPoolNumbers.RAMSES_USDC_WETH_VAULT,
      ArbitrumPoolNumbers.RAMSES_USDT_RAM_VAULT,
      ArbitrumPoolNumbers.RAMSES_WBTC_RAM_VAULT,
      ArbitrumPoolNumbers.RAMSES_WETH_ARB_VAULT,
      ArbitrumPoolNumbers.RAMSES_WETH_ERN_VAULT,
      ArbitrumPoolNumbers.RAMSES_WETH_ICHI_VAULT,
      ArbitrumPoolNumbers.RAMSES_WETH_OATH_VAULT,
      ArbitrumPoolNumbers.RAMSES_WETH_RAM_VAULT,
      ArbitrumPoolNumbers.RAMSES_WETH_RAM_05_VAULT,
      ArbitrumPoolNumbers.RAMSES_WETH_USDC_VAULT,
      // Sushi
      ArbitrumPoolNumbers.SUSHISWAP_WBTC_ICHI_VAULT,
    ],
    [ChainId.Avalanche]: [],
    [ChainId.Bsc]: [
      // Pancake
      BscPoolNumbers.AIOZ_USDT_VAULT,
      BscPoolNumbers.AIOZ_WBNB_VAULT,
      BscPoolNumbers.BTCB_CAKE_VAULT,
      BscPoolNumbers.BTCB_USDT_VAULT,
      BscPoolNumbers.CAKE_USDT_VAULT,
      BscPoolNumbers.CAKE_WBNB_VAULT,
      BscPoolNumbers.ETH_CAKE_VAULT,
      BscPoolNumbers.MUBI_WBNB_VAULT,
      BscPoolNumbers.ORDI_WBNB_VAULT,
      BscPoolNumbers.SATS_WBNB_VAULT,
      BscPoolNumbers.USDC_ETH_VAULT,
      BscPoolNumbers.USDT_AIOZ_VAULT,
      BscPoolNumbers.USDT_CAKE_VAULT,
      BscPoolNumbers.USDT_WBNB_VAULT,
      BscPoolNumbers.WBNB_AIOZ_VAULT,
      BscPoolNumbers.WBNB_CAKE_VAULT,
      // Thena
      BscPoolNumbers.THENA_BTCB_THE_VAULT,
      BscPoolNumbers.THENA_ETH_THE_VAULT,
      BscPoolNumbers.THENA_FRAX_USDC_VAULT,
      BscPoolNumbers.THENA_FRXETH_ETH_VAULT,
      BscPoolNumbers.THENA_HBR_USDT_VAULT,
      BscPoolNumbers.THENA_OATH_WBNB_VAULT,
      BscPoolNumbers.THENA_USDC_THE_VAULT,
      BscPoolNumbers.THENA_USDT_ABOND_VAULT,
      BscPoolNumbers.THENA_USDT_HBR_VAULT,
      BscPoolNumbers.THENA_USDT_THE_VAULT,
      BscPoolNumbers.THENA_USDT_XCAD_VAULT,
      BscPoolNumbers.THENA_WBNB_ABOND_VAULT,
      BscPoolNumbers.THENA_WBNB_ICHI_VAULT,
      BscPoolNumbers.THENA_WBNB_OATH_VAULT,
      BscPoolNumbers.THENA_WBNB_THE_VAULT,
      // Bsc-uni v3
      BscPoolNumbers.UNIV3_ICHI_WBNB_VAULT,
    ],
    [ChainId.Eon]: [
      EonPoolNumbers.ASCENT_USDC_WZEN_VAULT,
      EonPoolNumbers.ASCENT_USDT_WZEN_VAULT,
      EonPoolNumbers.ASCENT_WAVAX_WZEN_VAULT,
      EonPoolNumbers.ASCENT_WBTC_WZEN_VAULT,
      EonPoolNumbers.ASCENT_WETH_USDC_VAULT,
      EonPoolNumbers.ASCENT_WETH_WBTC_VAULT,
      EonPoolNumbers.ASCENT_WETH_WZEN_VAULT,
    ],
    [ChainId.Fantom]: [
      FantomPoolNumbers.EQUALIZER_AXLUSDC_WFTM_VAULT,
      FantomPoolNumbers.EQUALIZER_USDC_WFTM_VAULT,
      FantomPoolNumbers.EQUALIZER_WFTM_AXLUSDC_VAULT,
      FantomPoolNumbers.EQUALIZER_WFTM_USDC_VAULT,
    ],
    [ChainId.Linea]: [
      LineaPoolNumbers.LYNEX_USDC_WETH_VAULT,
      LineaPoolNumbers.LYNEX_WBTC_WETH_VAULT,
      LineaPoolNumbers.LYNEX_WETH_USDC_VAULT,
      LineaPoolNumbers.LYNEX_WETH_WBTC_VAULT,
    ],
    [ChainId.Mantle]: [
      MantlePoolNumbers.CLEO_WMNT_CLEO_VAULT,
    ],
    [ChainId.opBNB]: [
      OpBnbPoolNumbers.THENA_BTCB_ETH_VAULT,
      OpBnbPoolNumbers.THENA_BTCB_USDT_VAULT,
      OpBnbPoolNumbers.THENA_ETH_BTCB_VAULT,
      OpBnbPoolNumbers.THENA_ETH_USDT_VAULT,
      OpBnbPoolNumbers.THENA_USDT_BTCB_VAULT,
      OpBnbPoolNumbers.THENA_USDT_ETH_VAULT,
      OpBnbPoolNumbers.THENA_USDT_WBNB_VAULT,
      OpBnbPoolNumbers.THENA_WBNB_ETH_VAULT,
    ],
    [ChainId.zkEVM]: [
      ZkEvmPoolNumbers.ZERO_MATIC_ZERO_VAULT,
      ZkEvmPoolNumbers.ZERO_USDC_WETH_VAULT,
      ZkEvmPoolNumbers.ZERO_USDC_ZERO_VAULT,
      ZkEvmPoolNumbers.ZERO_USDT_ZERO_VAULT,
      ZkEvmPoolNumbers.ZERO_WBTC_WETH_VAULT,
      ZkEvmPoolNumbers.ZERO_WBTC_ZERO_VAULT,
      ZkEvmPoolNumbers.ZERO_WETH_USDC_VAULT,
      ZkEvmPoolNumbers.ZERO_WETH_WBTC_VAULT,
      ZkEvmPoolNumbers.ZERO_WETH_ZERO_VAULT,
    ],
    [ChainId.zkSync]: [
      ZkSyncPoolNumbers.PANCAKESWAP_USDT_WETH_VAULT,
      ZkSyncPoolNumbers.PANCAKESWAP_WETH_USDC_VAULT,
    ],
    [ChainId.Mumbai]: [
      MumbaiPoolNumbers.ONE_BTC_ICHI_VAULT
    ],
  },
  [PoolGroupName.UNDERLYING_VAULTS]: {
    [ChainId.Mainnet]: [
      MainnetPoolNumbers.ONE_BTC_VAULT_LEGACY
    ],
    [ChainId.Polygon]: [],
    [ChainId.Arbitrum]: [],
    [ChainId.Avalanche]: [],
    [ChainId.Bsc]: [],
    [ChainId.Eon]: [],
    [ChainId.Fantom]: [],
    [ChainId.Linea]: [],
    [ChainId.Mantle]: [],
    [ChainId.opBNB]: [],
    [ChainId.zkEVM]: [],
    [ChainId.zkSync]: [],
    [ChainId.Mumbai]: [],
  },
  [PoolGroupName.UPCOMING_POOLS]: {
    [ChainId.Mainnet]: [],
    [ChainId.Polygon]: [],
    [ChainId.Arbitrum]: [],
    [ChainId.Avalanche]: [],
    [ChainId.Bsc]: [],
    [ChainId.Eon]: [],
    [ChainId.Fantom]: [],
    [ChainId.Linea]: [],
    [ChainId.Mantle]: [],
    [ChainId.opBNB]: [],
    [ChainId.zkEVM]: [],
    [ChainId.zkSync]: [],
    [ChainId.Mumbai]: [],
  },
  [PoolGroupName.MIGRATING_POOLS]: {
    [ChainId.Mainnet]: [],
    [ChainId.Polygon]: [],
    [ChainId.Arbitrum]: [],
    [ChainId.Avalanche]: [],
    [ChainId.Bsc]: [],
    [ChainId.Eon]: [],
    [ChainId.Fantom]: [],
    [ChainId.Linea]: [],
    [ChainId.Mantle]: [],
    [ChainId.opBNB]: [],
    [ChainId.zkEVM]: [],
    [ChainId.zkSync]: [],
    [ChainId.Mumbai]: [],
  },
  [PoolGroupName.RETIRED_POOLS]: {
    [ChainId.Mainnet]: [],
    [ChainId.Polygon]: [],
    [ChainId.Arbitrum]: [],
    [ChainId.Avalanche]: [],
    [ChainId.Bsc]: [],
    [ChainId.Eon]: [],
    [ChainId.Fantom]: [],
    [ChainId.Linea]: [],
    [ChainId.Mantle]: [],
    [ChainId.opBNB]: [],
    [ChainId.zkEVM]: [],
    [ChainId.zkSync]: [],
    [ChainId.Mumbai]: [],
  },

  // Pools in the UNRETIRED_POOLS will show up even if APR == 0
  // used only in retired app
  [PoolGroupName.UNRETIRED_POOLS]: {
    [ChainId.Mainnet]: [
      MainnetPoolNumbers._80_20_ICHI_ETH,
      MainnetPoolNumbers['1INCH_VAULT'],
      MainnetPoolNumbers.AAVE_VAULT,
      MainnetPoolNumbers.ALLY_VAULT,
      MainnetPoolNumbers.ASTO_VAULT,
      MainnetPoolNumbers.BANK_VAULT,
      MainnetPoolNumbers.BAT_VAULT,
      MainnetPoolNumbers.BIT_VAULT,
      MainnetPoolNumbers.BNT_VAULT,
      MainnetPoolNumbers.BOBA_VAULT,
      MainnetPoolNumbers.CEL_VAULT,
      MainnetPoolNumbers.CEL_VAULT_LEGACY,
      MainnetPoolNumbers.CHO_VAULT,
      MainnetPoolNumbers.COC_VAULT,
      MainnetPoolNumbers.COC_USDC_VAULT,
      MainnetPoolNumbers.COC_ETH_VAULT,
      MainnetPoolNumbers.COMP_VAULT,
      MainnetPoolNumbers.COW_VAULT,
      MainnetPoolNumbers.FIDU_VAULT,
      MainnetPoolNumbers.FRAX_VAULT,
      MainnetPoolNumbers.FUSE_ICHI_VAULT,
      MainnetPoolNumbers.FXS_VAULT,
      MainnetPoolNumbers.GIV_VAULT,
      MainnetPoolNumbers.GNO_VAULT,
      MainnetPoolNumbers.GNO_VAULT_LEGACY,
      MainnetPoolNumbers.HOME_VAULT,
      MainnetPoolNumbers.ICHI_1INCH,
      MainnetPoolNumbers.ICHI_BNT,
      MainnetPoolNumbers.ICHI_BNT_V3,
      MainnetPoolNumbers.ICHI_ETH_UNI_V2,
      MainnetPoolNumbers.IMX_VAULT,
      MainnetPoolNumbers.LDO_VAULT,
      MainnetPoolNumbers.LINK_VAULT,
      MainnetPoolNumbers.MIDAS_VAULT,
      MainnetPoolNumbers.MKR_VAULT,
      MainnetPoolNumbers.OGN_VAULT,
      MainnetPoolNumbers.ONE_1INCH,
      MainnetPoolNumbers.ONE_BTC_DEPOSIT,
      MainnetPoolNumbers.ONE_BTC_VAULT_LEGACY,
      MainnetPoolNumbers.ONE_BTC_VAULT_RARI,
      MainnetPoolNumbers.ONE_DODO,
      MainnetPoolNumbers.ONE_FIL,
      MainnetPoolNumbers.ONE_FOX,
      MainnetPoolNumbers.ONE_FOX_VAULT,
      MainnetPoolNumbers.ONE_GIV,
      MainnetPoolNumbers.ONE_MPH,
      MainnetPoolNumbers.ONE_OJA_VAULT,
      MainnetPoolNumbers.ONE_PERL,
      MainnetPoolNumbers.ONE_ICHI_VAULT,
      MainnetPoolNumbers.ONE_UNI,
      MainnetPoolNumbers.ONE_UNI_FARM,
      MainnetPoolNumbers.ONE_UNI_VAULT,
      MainnetPoolNumbers.ONE_UNI_VAULT_LP,
      MainnetPoolNumbers.ONE_FUSE_VAULT,
      MainnetPoolNumbers.ONE_WING,
      MainnetPoolNumbers.ONE_WING_VAULT,
      MainnetPoolNumbers.OUSD_VAULT,
      MainnetPoolNumbers.QRDO_ICHI_VAULT,
      MainnetPoolNumbers.QRDO_VAULT,
      MainnetPoolNumbers.SFRXETH_VAULT,
      MainnetPoolNumbers.SHIB_VAULT,
      MainnetPoolNumbers.SUSHI_VAULT,
      MainnetPoolNumbers.SWISE_VAULT,
      MainnetPoolNumbers.TBTC_WETH_VAULT,
      MainnetPoolNumbers.UNI_VAULT, 
      MainnetPoolNumbers.USDC_VAULT,
      MainnetPoolNumbers.WBTC_VAULT,
      MainnetPoolNumbers.WBTC_VAULT_LEGACY,
      MainnetPoolNumbers.WETH_VAULT,
      MainnetPoolNumbers.WNXM_VAULT,
      MainnetPoolNumbers.WNXM_VAULT_LEGACY,
      MainnetPoolNumbers.YFI_VAULT,
      MainnetPoolNumbers.ZRX_VAULT,
    ],
    [ChainId.Polygon]: [
      PolygonPoolNumbers.GOVI_VAULT, 
      PolygonPoolNumbers.ONE_BTC_VAULT, 
      PolygonPoolNumbers.TRADE_USDT_VAULT,
      PolygonPoolNumbers.USDC_VAULT,
      PolygonPoolNumbers.WBTC_VAULT, 
    ],
    [ChainId.Arbitrum]: [],
    [ChainId.Avalanche]: [],
    [ChainId.Bsc]: [],
    [ChainId.Eon]: [],
    [ChainId.Fantom]: [],
    [ChainId.Linea]: [],
    [ChainId.Mantle]: [],
    [ChainId.opBNB]: [],
    [ChainId.zkEVM]: [],
    [ChainId.zkSync]: [],
    [ChainId.Mumbai]: [
      MumbaiPoolNumbers.ONE_BTC_ICHI_VAULT
    ],
  },
  [PoolGroupName.ONE_INCH_POOLS]: {
    [ChainId.Mainnet]: [
      MainnetPoolNumbers.ICHI_1INCH,
    ],
    [ChainId.Polygon]: [],
    [ChainId.Arbitrum]: [],
    [ChainId.Avalanche]: [],
    [ChainId.Bsc]: [],
    [ChainId.Eon]: [],
    [ChainId.Fantom]: [],
    [ChainId.Linea]: [],
    [ChainId.Mantle]: [],
    [ChainId.opBNB]: [],
    [ChainId.zkEVM]: [],
    [ChainId.zkSync]: [],
    [ChainId.Mumbai]: [],
  },
  [PoolGroupName.BALANCER_POOLS]: {
    [ChainId.Mainnet]: [
      MainnetPoolNumbers._80_20_ICHI_ETH,
    ],
    [ChainId.Polygon]: [],
    [ChainId.Arbitrum]: [],
    [ChainId.Avalanche]: [],
    [ChainId.Bsc]: [],
    [ChainId.Eon]: [],
    [ChainId.Fantom]: [],
    [ChainId.Linea]: [],
    [ChainId.Mantle]: [],
    [ChainId.opBNB]: [],
    [ChainId.zkEVM]: [],
    [ChainId.zkSync]: [],
    [ChainId.Mumbai]: [],
  },
  [PoolGroupName.BANCOR_POOLS_V2]: {
    // bancorPoolsV2: [14, 1006, 10003],
    [ChainId.Mainnet]: [
      MainnetPoolNumbers.ICHI_BNT,
    ],
    [ChainId.Polygon]: [],
    [ChainId.Arbitrum]: [],
    [ChainId.Avalanche]: [],
    [ChainId.Bsc]: [],
    [ChainId.Eon]: [],
    [ChainId.Fantom]: [],
    [ChainId.Linea]: [],
    [ChainId.Mantle]: [],
    [ChainId.opBNB]: [],
    [ChainId.zkEVM]: [],
    [ChainId.zkSync]: [],
    [ChainId.Mumbai]: [],
  },
  [PoolGroupName.BANCOR_POOLS_V3]: {
    [ChainId.Mainnet]: [
      MainnetPoolNumbers.ICHI_BNT_V3
    ],
    [ChainId.Polygon]: [],
    [ChainId.Arbitrum]: [],
    [ChainId.Avalanche]: [],
    [ChainId.Bsc]: [],
    [ChainId.Eon]: [],
    [ChainId.Fantom]: [],
    [ChainId.Linea]: [],
    [ChainId.Mantle]: [],
    [ChainId.opBNB]: [],
    [ChainId.zkEVM]: [],
    [ChainId.zkSync]: [],
    [ChainId.Mumbai]: [],
  },
  [PoolGroupName.UNI_POOLS]: {
    [ChainId.Mainnet]: [
      MainnetPoolNumbers.ICHI_ETH_UNI_V2
    ],
    [ChainId.Polygon]: [],
    [ChainId.Arbitrum]: [],
    [ChainId.Avalanche]: [],
    [ChainId.Bsc]: [],
    [ChainId.Eon]: [],
    [ChainId.Fantom]: [],
    [ChainId.Linea]: [],
    [ChainId.Mantle]: [],
    [ChainId.opBNB]: [],
    [ChainId.zkEVM]: [],
    [ChainId.zkSync]: [],
    [ChainId.Mumbai]: [],
  },
  [PoolGroupName.DODO_POOLS]: {
    [ChainId.Mainnet]: [
      MainnetPoolNumbers.ONE_DODO_USDC_BSC_MAINNET,
      MainnetPoolNumbers.ONE_DODO_USDC_MAINNET, 
    ],
    [ChainId.Polygon]: [],
    [ChainId.Arbitrum]: [],
    [ChainId.Avalanche]: [],
    [ChainId.Bsc]: [],
    [ChainId.Eon]: [],
    [ChainId.Fantom]: [],
    [ChainId.Linea]: [],
    [ChainId.Mantle]: [],
    [ChainId.opBNB]: [],
    [ChainId.zkEVM]: [],
    [ChainId.zkSync]: [],
    [ChainId.Mumbai]: [],
  },
  [PoolGroupName.RARI_ASSETS]: {
    [ChainId.Mainnet]: [
      MainnetPoolNumbers.ONE_BTC_DEPOSIT,
      MainnetPoolNumbers.ONE_BTC_VAULT_RARI, 
      MainnetPoolNumbers.ONE_UNI, 
      MainnetPoolNumbers.ONE_UNI_VAULT, 
    ],
    [ChainId.Polygon]: [],
    [ChainId.Arbitrum]: [],
    [ChainId.Avalanche]: [],
    [ChainId.Bsc]: [],
    [ChainId.Eon]: [],
    [ChainId.Fantom]: [],
    [ChainId.Linea]: [],
    [ChainId.Mantle]: [],
    [ChainId.opBNB]: [],
    [ChainId.zkEVM]: [],
    [ChainId.zkSync]: [],
    [ChainId.Mumbai]: [],
  },
  // Pools in the LEGACY_POOLS will only show in old.ichi.org
  [PoolGroupName.LEGACY_POOLS]: {
    [ChainId.Mainnet]: [
      MainnetPoolNumbers._80_20_ICHI_ETH,
      MainnetPoolNumbers.AAVE_VAULT,
      MainnetPoolNumbers.ASTO_VAULT,
      MainnetPoolNumbers.BANK_VAULT,
      MainnetPoolNumbers.BAT_VAULT,
      MainnetPoolNumbers.BIT_VAULT,
      MainnetPoolNumbers.BNT_VAULT,
      MainnetPoolNumbers.BOBA_VAULT,
      MainnetPoolNumbers.CEL_VAULT_LEGACY,
      MainnetPoolNumbers.CHO_VAULT,
      MainnetPoolNumbers.COC_VAULT,
      MainnetPoolNumbers.COC_USDC_VAULT,
      MainnetPoolNumbers.COC_ETH_VAULT,
      MainnetPoolNumbers.COMP_VAULT,
      MainnetPoolNumbers.COW_VAULT,
      MainnetPoolNumbers.FIDU_VAULT,
      MainnetPoolNumbers.FRAX_VAULT,
      MainnetPoolNumbers.FXS_VAULT,
      MainnetPoolNumbers.GNO_VAULT_LEGACY,
      MainnetPoolNumbers.ICHI_1INCH,
      MainnetPoolNumbers.ICHI_BNT,
      MainnetPoolNumbers.ICHI_BNT_V3,
      MainnetPoolNumbers.ICHI_ETH_SUSHI,
      MainnetPoolNumbers.ICHI_ETH_UNI_V2,
      MainnetPoolNumbers.IMX_VAULT,
      MainnetPoolNumbers.LDO_VAULT,
      MainnetPoolNumbers.LINK_VAULT,
      MainnetPoolNumbers.MIDAS_VAULT,
      MainnetPoolNumbers.MKR_VAULT,
      MainnetPoolNumbers.OGN_VAULT,
      MainnetPoolNumbers.ONE_1INCH,
      MainnetPoolNumbers.ONE_BTC_DEPOSIT,
      MainnetPoolNumbers.ONE_BTC_VAULT_LEGACY,
      MainnetPoolNumbers.ONE_BTC_VAULT_RARI,
      MainnetPoolNumbers.ONE_DODO,
      MainnetPoolNumbers.ONE_DODO_USDC_BSC_MAINNET,
      MainnetPoolNumbers.ONE_DODO_USDC_MAINNET,
      MainnetPoolNumbers.ONE_FIL,
      MainnetPoolNumbers.ONE_FOX,
      MainnetPoolNumbers.ONE_FOX_VAULT,
      MainnetPoolNumbers.ONE_FUSE_VAULT,
      MainnetPoolNumbers.ONE_MPH,
      MainnetPoolNumbers.ONE_OJA_VAULT,
      MainnetPoolNumbers.ONE_PERL,
      MainnetPoolNumbers.ONE_UNI,
      MainnetPoolNumbers.ONE_UNI_VAULT,
      MainnetPoolNumbers.ONE_UNI_VAULT_LP,
      MainnetPoolNumbers.ONE_WING,
      MainnetPoolNumbers.ONE_WING_VAULT,
      MainnetPoolNumbers.OUSD_VAULT,
      MainnetPoolNumbers.QRDO_ICHI_VAULT,
      MainnetPoolNumbers.SFRXETH_VAULT,
      MainnetPoolNumbers.SHIB_VAULT,
      MainnetPoolNumbers.SUSHI_VAULT,
      MainnetPoolNumbers.SWISE_VAULT,
      MainnetPoolNumbers.TBTC_WETH_VAULT,
      MainnetPoolNumbers.UNI_VAULT,
      MainnetPoolNumbers.WBTC_VAULT_LEGACY,
      MainnetPoolNumbers.WNXM_VAULT_LEGACY,
      MainnetPoolNumbers.ZRX_VAULT,
    ],
    [ChainId.Polygon]: [
      PolygonPoolNumbers.TRADE_USDT_VAULT,
      PolygonPoolNumbers.WETH_FBX_VAULT, 
    ],
    [ChainId.Arbitrum]: [],
    [ChainId.Avalanche]: [],
    [ChainId.Bsc]: [],
    [ChainId.Eon]: [],
    [ChainId.Fantom]: [],
    [ChainId.Linea]: [],
    [ChainId.Mantle]: [],
    [ChainId.opBNB]: [],
    [ChainId.zkEVM]: [],
    [ChainId.zkSync]: [],
    [ChainId.Mumbai]: [],
  },
  // Vaults that are not processed in api-updater using standard multicall flow
  [PoolGroupName.NONSTANDARD_VAULTS]: {
    [ChainId.Mainnet]: [
      MainnetPoolNumbers.CEL_VAULT_LEGACY,
      MainnetPoolNumbers.GNO_VAULT_LEGACY,
      MainnetPoolNumbers.ONE_BTC_DEPOSIT,
      MainnetPoolNumbers.ONE_BTC_VAULT_LEGACY,
      MainnetPoolNumbers.ONE_BTC_VAULT_RARI,
      MainnetPoolNumbers.ONE_FOX_VAULT,
      MainnetPoolNumbers.ONE_FUSE_VAULT,
      MainnetPoolNumbers.ONE_OJA_VAULT,
      MainnetPoolNumbers.ONE_UNI_VAULT,
      MainnetPoolNumbers.ONE_UNI_VAULT_LP,
      MainnetPoolNumbers.ONE_WING_VAULT,
      MainnetPoolNumbers.WBTC_VAULT_LEGACY,
      MainnetPoolNumbers.WNXM_VAULT_LEGACY,
    ],
    [ChainId.Polygon]: [],
    [ChainId.Arbitrum]: [],
    [ChainId.Avalanche]: [],
    [ChainId.Bsc]: [],
    [ChainId.Eon]: [],
    [ChainId.Fantom]: [],
    [ChainId.Linea]: [],
    [ChainId.Mantle]: [],
    [ChainId.opBNB]: [],
    [ChainId.zkEVM]: [],
    [ChainId.zkSync]: [],
    [ChainId.Mumbai]: [],
  },
  // These vaults don't show in either main app or legacy app.
  // They are available by direct link
  [PoolGroupName.HIDDEN_VAULTS]: {
    [ChainId.Mainnet]: [
      MainnetPoolNumbers.PANCAKESWAP_WETH_USDT_VAULT,
      MainnetPoolNumbers.PANCAKESWAP_WETH_SWETH_VAULT,
    ], 
    [ChainId.Polygon]: [
      // QuickSwap
      PolygonPoolNumbers.QUICKSWAP_A3A_USDC_VAULT,
      PolygonPoolNumbers.QUICKSWAP_AAVE_WETH_VAULT,
      PolygonPoolNumbers.QUICKSWAP_LINK_WETH_VAULT,
      PolygonPoolNumbers.QUICKSWAP_MATICX_WMATIC_VAULT,
      PolygonPoolNumbers.QUICKSWAP_USDC_A3A_VAULT,
      PolygonPoolNumbers.QUICKSWAP_USDC_ABOND_VAULT,
      PolygonPoolNumbers.QUICKSWAP_USDC_QUICK_VAULT,
      PolygonPoolNumbers.QUICKSWAP_USDC_WEFI_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WBTC_USDC_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WBTC_WETH_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WEFI_USDC_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WEFI_WETH_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WETH_FUSE_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WETH_ICHI_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WETH_QUICK_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WETH_USDT_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WETH_WEFI_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WMATIC_ABOND_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WMATIC_ICHI_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WMATIC_QUICK_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WMATIC_USDT_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WMATIC_WETH_VAULT,
      // Retro
      PolygonPoolNumbers.RETRO_AGEUR_RETRO_VAULT,
      PolygonPoolNumbers.RETRO_AGEUR_USDC_VAULT,
      PolygonPoolNumbers.RETRO_CASH_AXLLQDR_VAULT, 
      PolygonPoolNumbers.RETRO_CASH_ICHI_VAULT,
      PolygonPoolNumbers.RETRO_CASH_RETRO_VAULT,
      PolygonPoolNumbers.RETRO_CASH_WETH_VAULT, 
      PolygonPoolNumbers.RETRO_CASH_WMATIC_VAULT, 
      PolygonPoolNumbers.RETRO_FRXETH_FRAX_VAULT,
      PolygonPoolNumbers.RETRO_FRXETH_WMATIC_VAULT,
      PolygonPoolNumbers.RETRO_ICHI_CASH_VAULT,
      PolygonPoolNumbers.RETRO_ICHI_RETRO_VAULT,
      PolygonPoolNumbers.RETRO_JRT_WETH_VAULT, 
      PolygonPoolNumbers.RETRO_LINK_RETRO_VAULT,
      PolygonPoolNumbers.RETRO_MATICX_CASH_VAULT, 
      PolygonPoolNumbers.RETRO_MATICX_WMATIC_01_VAULT,
      PolygonPoolNumbers.RETRO_MATICX_WMATIC_05_VAULT,
      PolygonPoolNumbers.RETRO_MIMATIC_RETRO_VAULT,
      PolygonPoolNumbers.RETRO_OATH_WETH_VAULT,
      PolygonPoolNumbers.RETRO_ORETRO_RETRO_VAULT,
      PolygonPoolNumbers.RETRO_RETRO_LIVERETRO_VAULT,
      PolygonPoolNumbers.RETRO_STMATIC_RETRO_VAULT,
      PolygonPoolNumbers.RETRO_STMATIC_WMATIC_VAULT,
      PolygonPoolNumbers.RETRO_USDC_AGEUR_VAULT,
      PolygonPoolNumbers.RETRO_USDC_MIMATIC_VAULT,
      PolygonPoolNumbers.RETRO_USDC_RETRO_VAULT,
      PolygonPoolNumbers.RETRO_USDC_WETH_VAULT, 
      PolygonPoolNumbers.RETRO_USDC_WMATIC_VAULT, 
      PolygonPoolNumbers.RETRO_USDT_RETRO_VAULT,
      PolygonPoolNumbers.RETRO_USDT_WMATIC_VAULT, 
      PolygonPoolNumbers.RETRO_WBTC_RETRO_VAULT,
      PolygonPoolNumbers.RETRO_WBTC_USDC_VAULT,
      PolygonPoolNumbers.RETRO_WBTC_WETH_VAULT, 
      PolygonPoolNumbers.RETRO_WETH_ERN_VAULT,
      PolygonPoolNumbers.RETRO_WETH_OATH_VAULT,
      PolygonPoolNumbers.RETRO_WETH_RETRO_VAULT,
      PolygonPoolNumbers.RETRO_WETH_USDC_VAULT,
      PolygonPoolNumbers.RETRO_WETH_WBTC_VAULT, 
      PolygonPoolNumbers.RETRO_WETH_WMATIC_VAULT, 
      PolygonPoolNumbers.RETRO_WMATIC_ICHI_VAULT,
      PolygonPoolNumbers.RETRO_WMATIC_MATICX_01_VAULT,
      PolygonPoolNumbers.RETRO_WMATIC_MATICX_05_VAULT,
      PolygonPoolNumbers.RETRO_WMATIC_RETRO_VAULT,
      PolygonPoolNumbers.RETRO_WMATIC_STMATIC_VAULT,
      PolygonPoolNumbers.RETRO_WMATIC_USDC_VAULT, 
      PolygonPoolNumbers.RETRO_WMATIC_USDC_05_VAULT,
      PolygonPoolNumbers.RETRO_WMATIC_WETH_VAULT, 
    ],
    [ChainId.Arbitrum]: [
      // Horiza
      ArbitrumPoolNumbers.HORIZA_USDC_ICHI_VAULT,
      ArbitrumPoolNumbers.HORIZA_WETH_ICHI_VAULT,
      // Ramses
      ArbitrumPoolNumbers.RAMSES_ARB_RAM_VAULT,
      ArbitrumPoolNumbers.RAMSES_ARB_USDC_VAULT,
      ArbitrumPoolNumbers.RAMSES_ARB_WETH_VAULT,
      ArbitrumPoolNumbers.RAMSES_FRAX_USDC_VAULT,
      ArbitrumPoolNumbers.RAMSES_FRXETH_WETH_VAULT,
      ArbitrumPoolNumbers.RAMSES_GRAI_RAM_VAULT,
      ArbitrumPoolNumbers.RAMSES_GRAI_WETH_VAULT,
      ArbitrumPoolNumbers.RAMSES_ICHI_RAM_VAULT,
      ArbitrumPoolNumbers.RAMSES_OATH_WETH_VAULT,
      ArbitrumPoolNumbers.RAMSES_SFRAX_FRAX_VAULT,
      ArbitrumPoolNumbers.RAMSES_USDC_ARB_VAULT,
      ArbitrumPoolNumbers.RAMSES_USDC_WETH_VAULT,
      ArbitrumPoolNumbers.RAMSES_USDT_RAM_VAULT,
      ArbitrumPoolNumbers.RAMSES_WBTC_RAM_VAULT,
      ArbitrumPoolNumbers.RAMSES_WETH_ARB_VAULT,
      ArbitrumPoolNumbers.RAMSES_WETH_ERN_VAULT,
      ArbitrumPoolNumbers.RAMSES_WETH_ICHI_VAULT,
      ArbitrumPoolNumbers.RAMSES_WETH_OATH_VAULT,
      ArbitrumPoolNumbers.RAMSES_WETH_RAM_VAULT,
      ArbitrumPoolNumbers.RAMSES_WETH_RAM_05_VAULT,
      ArbitrumPoolNumbers.RAMSES_WETH_USDC_VAULT,
      // Sushi
      ArbitrumPoolNumbers.SUSHISWAP_WBTC_ICHI_VAULT,
    ],
    [ChainId.Avalanche]: [],
    [ChainId.Bsc]: [
      BscPoolNumbers.CAKE_USDT_VAULT, 
      BscPoolNumbers.CAKE_WBNB_VAULT, 
      // BscPoolNumbers.USDT_CAKE_VAULT, 
      // BscPoolNumbers.USDT_WBNB_VAULT, 
      // BscPoolNumbers.WBNB_CAKE_VAULT, 
      // Thena
      BscPoolNumbers.THENA_BTCB_THE_VAULT,
      BscPoolNumbers.THENA_ETH_THE_VAULT,
      BscPoolNumbers.THENA_FRAX_USDC_VAULT,
      BscPoolNumbers.THENA_FRXETH_ETH_VAULT,
      BscPoolNumbers.THENA_HBR_USDT_VAULT,
      BscPoolNumbers.THENA_OATH_WBNB_VAULT,
      BscPoolNumbers.THENA_USDC_THE_VAULT,
      BscPoolNumbers.THENA_USDT_ABOND_VAULT,
      BscPoolNumbers.THENA_USDT_HBR_VAULT,
      BscPoolNumbers.THENA_USDT_THE_VAULT,
      BscPoolNumbers.THENA_USDT_XCAD_VAULT,
      BscPoolNumbers.THENA_WBNB_ABOND_VAULT,
      BscPoolNumbers.THENA_WBNB_ICHI_VAULT,
      BscPoolNumbers.THENA_WBNB_OATH_VAULT,
      BscPoolNumbers.THENA_WBNB_THE_VAULT,
    ],
    [ChainId.Eon]: [
      EonPoolNumbers.ASCENT_USDC_WZEN_VAULT,
      EonPoolNumbers.ASCENT_USDT_WZEN_VAULT,
      EonPoolNumbers.ASCENT_WAVAX_WZEN_VAULT,
      EonPoolNumbers.ASCENT_WBTC_WZEN_VAULT,
      EonPoolNumbers.ASCENT_WETH_USDC_VAULT,
      EonPoolNumbers.ASCENT_WETH_WBTC_VAULT,
      EonPoolNumbers.ASCENT_WETH_WZEN_VAULT,
    ],
    [ChainId.Fantom]: [
      FantomPoolNumbers.EQUALIZER_AXLUSDC_WFTM_VAULT,
      FantomPoolNumbers.EQUALIZER_USDC_WFTM_VAULT,
      FantomPoolNumbers.EQUALIZER_WFTM_AXLUSDC_VAULT,
      FantomPoolNumbers.EQUALIZER_WFTM_USDC_VAULT,
    ],
    [ChainId.Linea]: [
      LineaPoolNumbers.LYNEX_USDC_WETH_VAULT,
      LineaPoolNumbers.LYNEX_WBTC_WETH_VAULT,
      LineaPoolNumbers.LYNEX_WETH_USDC_VAULT,
      LineaPoolNumbers.LYNEX_WETH_WBTC_VAULT,
    ],
    [ChainId.Mantle]: [
      MantlePoolNumbers.CLEO_WMNT_CLEO_VAULT,
    ],
    [ChainId.opBNB]: [
      OpBnbPoolNumbers.THENA_BTCB_ETH_VAULT,
      OpBnbPoolNumbers.THENA_BTCB_USDT_VAULT,
      OpBnbPoolNumbers.THENA_ETH_BTCB_VAULT,
      OpBnbPoolNumbers.THENA_ETH_USDT_VAULT,
      OpBnbPoolNumbers.THENA_USDT_BTCB_VAULT,
      OpBnbPoolNumbers.THENA_USDT_ETH_VAULT,
      OpBnbPoolNumbers.THENA_USDT_WBNB_VAULT,
      OpBnbPoolNumbers.THENA_WBNB_ETH_VAULT,
    ],
    [ChainId.zkEVM]: [
      ZkEvmPoolNumbers.ZERO_MATIC_ZERO_VAULT,
      ZkEvmPoolNumbers.ZERO_USDC_WETH_VAULT,
      ZkEvmPoolNumbers.ZERO_USDC_ZERO_VAULT,
      ZkEvmPoolNumbers.ZERO_USDT_ZERO_VAULT,
      ZkEvmPoolNumbers.ZERO_WBTC_WETH_VAULT,
      ZkEvmPoolNumbers.ZERO_WBTC_ZERO_VAULT,
      ZkEvmPoolNumbers.ZERO_WETH_USDC_VAULT,
      ZkEvmPoolNumbers.ZERO_WETH_WBTC_VAULT,
      ZkEvmPoolNumbers.ZERO_WETH_ZERO_VAULT,
    ],
    [ChainId.zkSync]: [
      ZkSyncPoolNumbers.PANCAKESWAP_USDT_WETH_VAULT,
      ZkSyncPoolNumbers.PANCAKESWAP_WETH_USDC_VAULT,
    ],
    [ChainId.Mumbai]: [],
  },
  // Vaults that are not processed in api-updater using standard multicall flow
  [PoolGroupName.ALGEBRA_VAULTS]: {
    [ChainId.Mainnet]: [],
    [ChainId.Polygon]: [
      // QuickSwap
      PolygonPoolNumbers.QUICKSWAP_A3A_USDC_VAULT,
      PolygonPoolNumbers.QUICKSWAP_AAVE_WETH_VAULT,
      PolygonPoolNumbers.QUICKSWAP_LINK_WETH_VAULT,
      PolygonPoolNumbers.QUICKSWAP_MATICX_WMATIC_VAULT,
      PolygonPoolNumbers.QUICKSWAP_USDC_A3A_VAULT,
      PolygonPoolNumbers.QUICKSWAP_USDC_ABOND_VAULT,
      PolygonPoolNumbers.QUICKSWAP_USDC_QUICK_VAULT,
      PolygonPoolNumbers.QUICKSWAP_USDC_WEFI_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WBTC_USDC_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WBTC_WETH_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WEFI_USDC_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WEFI_WETH_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WETH_FUSE_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WETH_ICHI_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WETH_QUICK_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WETH_USDT_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WETH_WEFI_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WMATIC_ABOND_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WMATIC_ICHI_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WMATIC_QUICK_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WMATIC_USDT_VAULT,
      PolygonPoolNumbers.QUICKSWAP_WMATIC_WETH_VAULT,
    ],
    [ChainId.Arbitrum]: [],
    [ChainId.Avalanche]: [],
    [ChainId.Bsc]: [
      BscPoolNumbers.THENA_BTCB_THE_VAULT,
      BscPoolNumbers.THENA_ETH_THE_VAULT,
      BscPoolNumbers.THENA_FRAX_USDC_VAULT,
      BscPoolNumbers.THENA_FRXETH_ETH_VAULT,
      BscPoolNumbers.THENA_HBR_USDT_VAULT,
      BscPoolNumbers.THENA_OATH_WBNB_VAULT,
      BscPoolNumbers.THENA_USDC_THE_VAULT,
      BscPoolNumbers.THENA_USDT_ABOND_VAULT,
      BscPoolNumbers.THENA_USDT_HBR_VAULT,
      BscPoolNumbers.THENA_USDT_THE_VAULT,
      BscPoolNumbers.THENA_USDT_XCAD_VAULT,
      BscPoolNumbers.THENA_WBNB_ABOND_VAULT,
      BscPoolNumbers.THENA_WBNB_ICHI_VAULT,
      BscPoolNumbers.THENA_WBNB_OATH_VAULT,
      BscPoolNumbers.THENA_WBNB_THE_VAULT,
    ],
    [ChainId.Eon]: [],
    [ChainId.Fantom]: [],
    [ChainId.Linea]: [
      LineaPoolNumbers.LYNEX_USDC_WETH_VAULT,
      LineaPoolNumbers.LYNEX_WBTC_WETH_VAULT,
      LineaPoolNumbers.LYNEX_WETH_USDC_VAULT,
      LineaPoolNumbers.LYNEX_WETH_WBTC_VAULT,
    ],
    [ChainId.Mantle]: [],
    [ChainId.opBNB]: [
      OpBnbPoolNumbers.THENA_BTCB_ETH_VAULT,
      OpBnbPoolNumbers.THENA_BTCB_USDT_VAULT,
      OpBnbPoolNumbers.THENA_ETH_BTCB_VAULT,
      OpBnbPoolNumbers.THENA_ETH_USDT_VAULT,
      OpBnbPoolNumbers.THENA_USDT_BTCB_VAULT,
      OpBnbPoolNumbers.THENA_USDT_ETH_VAULT,
      OpBnbPoolNumbers.THENA_USDT_WBNB_VAULT,
      OpBnbPoolNumbers.THENA_WBNB_ETH_VAULT,
    ],
    [ChainId.zkEVM]: [],
    [ChainId.zkSync]: [],
    [ChainId.Mumbai]: [],
  },
};

export function getPool(poolName: PoolName, chainId: ChainId): Pool {
  const pool = PoolMapping[poolName] != null ? PoolMapping[poolName][chainId] : undefined;
  if (!pool) {
    throw new Error(`Could not find ${poolName} on ${chainId}`);
  }
  return pool;
}

export function getPools(chainId: ChainId): Pool[] {
  const names = Object.keys(PoolMapping);
  const vaults: Pool[] = [];
  for (let name of names) {
    if (chainId in PoolMapping[name]) {
      vaults.push(PoolMapping[name][chainId]);
    }
  }
  return vaults;
}
